const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const model = {};
vm.createContext(model);
vm.runInContext(fs.readFileSync(path.join(__dirname, '../Model.js'), 'utf8'), model);
const event = (name, epoch) => ({name, epoch, prayer: name !== 'Sunrise'});
const report = {events: [event('Isha', 0), event('Fajr', 100), event('Sunrise', 150), event('Dhuhr', 300), event('Isha', 500), event('Fajr', 800)]};
assert.equal(model.nextPrayer(report, 99).name, 'Fajr');
assert.equal(model.nextPrayer(report, 100).name, 'Dhuhr', 'sunrise must not become next prayer');
assert.equal(model.nextPrayer(report, 501).epoch, 800, 'after Isha, use tomorrow’s Fajr');
assert.equal(model.nextPrayer(report, 801), null, 'never invent tomorrow’s times');
assert.equal(model.progress(report, 200), 0.5);
assert.equal(model.progress(report, 100), 0);
assert.equal(model.countdown(-3, false), '00:00:00');
assert.equal(model.countdown(3661, false), '01:01:01');
assert.equal(model.timeLabel({time24: '00:05', time12: '12:05', period: 'AM'}, false), '12:05 AM');
const row = {name: 'Dhuhr', arabic: 'الظهر', time24: '11:47', time12: '11:47', period: 'AM', epoch: 5000};
assert.equal(model.formatBar(row, null, 0, {barPreset: 'custom', barFormat: '{name} {h}::{mm}:{ampm}'}), 'Dhuhr 11::47:am');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'time'}), '11:47 AM');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'name'}), 'Dhuhr');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'arabic'}), 'الظهر 11:47 AM');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'icon'}), '');
assert.equal(model.formatBar({...row, time24: '00:05', time12: '12:05'}, null, 0, {barPreset: 'custom', barFormat: '{h}/{hh}/{H}/{HH}:{mm}'}), '12/12/0/00:05');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'custom', barFormat: '{unknown}'}), '{unknown}');
assert.equal(model.retryDelay(1), 60);
assert.equal(model.retryDelay(2), 120);
assert.equal(model.retryDelay(20), 900);
assert.equal(model.duePrayer(report, 101, []).name, 'Fajr');
assert.equal(model.duePrayer(report, 201, []), null, 'waking late does not play old prayers');
assert.equal(model.duePrayer(report, 101, ['Fajr:100']), null, 'alert once');
assert.equal(model.duePrayer({events:[event('Sunrise', 150)]}, 151, []), null);
assert.equal(model.formatBar(row, null, 0, {barPreset: 'custom', barFormat: '{time24} / {time12}'}), '11:47 / 11:47 AM');
assert.equal(model.formatError('{name} {h}::{mm}:{ampm}'), '');
assert.ok(model.formatError('{minutes}').includes('Unknown token'));
assert.ok(model.formatError('{name').includes('matching'));
assert.ok(model.formatError('').includes('Enter a format'));
const options = model.barOptions(row, null, 0, {});
assert.equal(options.length, 9);
assert.ok(options.every(option => option.title && option.example));
assert.equal(options.find(option => option.value === 'time').example, '11:47 AM');
assert.equal(model.barTemplate({barPreset: '__proto__'}), '{name} {time}');
assert.equal(model.barTemplate({barPreset: 'constructor'}), '{name} {time}');
assert.equal(model.formatBar(row, null, 0, {barPreset: 'custom', barFormat: '{constructor}'}), '{constructor}');
assert.equal(model.audioVolume('invalid'), 35);
assert.equal(model.audioVolume(Infinity), 35);
assert.equal(model.audioVolume(-10), 0);
assert.equal(model.audioVolume(200), 100);
assert.equal(model.audioVolume('42'), 42);
console.log('39 prayer selection, format, retry, and alert checks passed.');
